export const languages = [
  {
    code: "ab",
    name: "Abkhaz",
    nativeName: "аҧсуа",
    countryCode: "GE",
  },
  {
    code: "aa",
    name: "Afar",
    nativeName: "Afaraf",
    countryCode: "ET",
  },
  {
    code: "af",
    name: "Afrikaans",
    nativeName: "Afrikaans",
    countryCode: "NA",
  },
  {
    code: "ak",
    name: "Akan",
    nativeName: "Akan",
    countryCode: "GH",
  },
  {
    code: "sq",
    name: "Albanian",
    nativeName: "Shqip",
    countryCode: "MK",
  },
  {
    code: "am",
    name: "Amharic",
    nativeName: "አማርኛ",
    countryCode: "EE",
  },
  {
    code: "ar",
    name: "Arabic",
    nativeName: "العربية",
    countryCode: "SA",
  },
  {
    code: "an",
    name: "Aragonese",
    nativeName: "Aragonés",
    countryCode: "ES",
  },
  {
    code: "hy",
    name: "Armenian",
    nativeName: "Հայերեն",
    countryCode: "ET",
  },
  {
    code: "as",
    name: "Assamese",
    nativeName: "অসমীয়া",
    countryCode: "IN",
  },
  {
    code: "av",
    name: "Avaric",
    nativeName: "авар мацӀ, магӀарул мацӀ",
    countryCode: "RU",
  },
  {
    code: "ae",
    name: "Avestan",
    nativeName: "avesta",
    countryCode: "AE",
  },
  {
    code: "ay",
    name: "Aymara",
    nativeName: "aymar aru",
    countryCode: "BO",
  },
  {
    code: "az",
    name: "Azerbaijani",
    nativeName: "azərbaycan dili",
    countryCode: "AZ",
  },
  {
    code: "bm",
    name: "Bambara",
    nativeName: "bamanankan",
    countryCode: "ML",
  },
  {
    code: "ba",
    name: "Bashkir",
    nativeName: "башҡорт теле",
    countryCode: "RU",
  },
  {
    code: "eu",
    name: "Basque",
    nativeName: "euskara, euskera",
    countryCode: "ES",
  },
  {
    code: "be",
    name: "Belarusian",
    nativeName: "Беларуская",
    countryCode: "BY",
  },
  {
    code: "bn",
    name: "Bengali",
    nativeName: "বাংলা",
    countryCode: "IN",
  },
  {
    code: "bh",
    name: "Bihari",
    nativeName: "भोजपुरी",
    countryCode: "IN",
  },
  {
    code: "bi",
    name: "Bislama",
    nativeName: "Bislama",
    countryCode: "VU",
  },
  {
    code: "bs",
    name: "Bosnian",
    nativeName: "bosanski jezik",
    countryCode: "BA",
  },
  {
    code: "br",
    name: "Breton",
    nativeName: "brezhoneg",
    countryCode: "FR",
  },
  {
    code: "bg",
    name: "Bulgarian",
    nativeName: "български език",
    countryCode: "BG",
  },
  {
    code: "my",
    name: "Burmese",
    nativeName: "ဗမာစာ",
    countryCode: "MM",
  },
  {
    code: "ca",
    name: "Catalan; Valencian",
    nativeName: "Català",
    countryCode: "ES",
  },
  {
    code: "ch",
    name: "Chamorro",
    nativeName: "Chamoru",
    countryCode: "US",
  },
  {
    code: "ce",
    name: "Chechen",
    nativeName: "нохчийн мотт",
    countryCode: "RU",
  },
  {
    code: "ny",
    name: "Chichewa; Chewa; Nyanja",
    nativeName: "chiCheŵa, chinyanja",
    countryCode: "MW",
  },
  {
    code: "zh",
    name: "Traditional Chinese",
    nativeName: "繁体",
    countryCode: "CN",
  },
  {
    code: "cn",
    name: "Simplified Chinese",
    nativeName: "简体",
    countryCode: "CN",
  },
  {
    code: "cv",
    name: "Chuvash",
    nativeName: "чӑваш чӗлхи",
    countryCode: "RU",
  },
  {
    code: "kw",
    name: "Cornish",
    nativeName: "Kernewek",
    countryCode: "GB",
  },
  {
    code: "co",
    name: "Corsican",
    nativeName: "corsu, lingua corsa",
    countryCode: "FR",
  },
  {
    code: "cr",
    name: "Cree",
    nativeName: "ᓀᐦᐃᔭᐍᐏᐣ",
    countryCode: "CA",
  },
  {
    code: "hr",
    name: "Croatian",
    nativeName: "hrvatski",
    countryCode: "HR",
  },
  {
    code: "cs",
    name: "Czech",
    nativeName: "česky, čeština",
    countryCode: "CZ",
  },
  {
    code: "da",
    name: "Danish",
    nativeName: "dansk",
    countryCode: "DK",
  },
  {
    code: "dv",
    name: "Divehi; Dhivehi; Maldivian;",
    nativeName: "ދިވެހި",
    countryCode: "MV",
  },
  {
    code: "nl",
    name: "Dutch",
    nativeName: "Nederlands, Vlaams",
    countryCode: "NL",
  },
  {
    code: "en",
    name: "English",
    nativeName: "English",
    countryCode: "US",
  },
  {
    code: "eo",
    name: "Esperanto",
    nativeName: "Esperanto",
    countryCode: "EO",
  },
  {
    code: "et",
    name: "Estonian",
    nativeName: "eesti, eesti keel",
    countryCode: "EE",
  },
  {
    code: "ee",
    name: "Ewe",
    nativeName: "Eʋegbe",
    countryCode: "GH",
  },
  {
    code: "fo",
    name: "Faroese",
    nativeName: "føroyskt",
    countryCode: "FO",
  },
  {
    code: "fj",
    name: "Fijian",
    nativeName: "vosa Vakaviti",
    countryCode: "FJ",
  },
  {
    code: "fi",
    name: "Finnish",
    nativeName: "suomi, suomen kieli",
    countryCode: "FI",
  },
  {
    code: "fr",
    name: "French",
    nativeName: "français, langue française",
    countryCode: "FR",
  },
  {
    code: "ff",
    name: "Fula; Fulah; Pulaar; Pular",
    nativeName: "Fulfulde, Pulaar, Pular",
    countryCode: "CF",
  },
  {
    code: "gl",
    name: "Galician",
    nativeName: "Galego",
    countryCode: "ES",
  },
  {
    code: "ka",
    name: "Georgian",
    nativeName: "ქართული",
    countryCode: "GE",
  },
  {
    code: "de",
    name: "German",
    nativeName: "Deutsch",
    countryCode: "DE",
  },
  {
    code: "el",
    name: "Greek, Modern",
    nativeName: "Ελληνικά",
    countryCode: "GR",
  },
  {
    code: "gn",
    name: "Guaraní",
    nativeName: "Avañeẽ",
    countryCode: "PY",
  },
  {
    code: "gu",
    name: "Gujarati",
    nativeName: "ગુજરાતી",
    countryCode: "IN",
  },
  {
    code: "ht",
    name: "Haitian; Haitian Creole",
    nativeName: "Kreyòl ayisyen",
    countryCode: "HT",
  },
  {
    code: "ha",
    name: "Hausa",
    nativeName: "Hausa, هَوُسَ",
    countryCode: "GH",
  },
  {
    code: "he",
    name: "Hebrew (modern)",
    nativeName: "עברית",
    countryCode: "IL",
  },
  {
    code: "hz",
    name: "Herero",
    nativeName: "Otjiherero",
    countryCode: "NA",
  },
  {
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी, हिंदी",
    countryCode: "IN",
  },
  {
    code: "ho",
    name: "Hiri Motu",
    nativeName: "Hiri Motu",
    countryCode: "PG",
  },
  {
    code: "hu",
    name: "Hungarian",
    nativeName: "Magyar",
    countryCode: "HU",
  },
  {
    code: "ia",
    name: "Interlingua",
    nativeName: "Interlingua",
    countryCode: "GO",
  },
  {
    code: "id",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    countryCode: "ID",
  },
  {
    code: "ie",
    name: "Interlingue",
    nativeName: "Originally called Occidental; then Interlingue after WWII",
    countryCode: "GO",
  },
  {
    code: "ga",
    name: "Irish",
    nativeName: "Gaeilge",
    countryCode: "IE",
  },
  {
    code: "ig",
    name: "Igbo",
    nativeName: "Asụsụ Igbo",
    countryCode: "NG",
  },
  {
    code: "ik",
    name: "Inupiaq",
    nativeName: "Iñupiaq, Iñupiatun",
    countryCode: "US",
  },
  {
    code: "io",
    name: "Ido",
    nativeName: "Ido",
    countryCode: "GO",
  },
  {
    code: "is",
    name: "Icelandic",
    nativeName: "Íslenska",
    countryCode: "IS",
  },
  {
    code: "it",
    name: "Italian",
    nativeName: "Italiano",
    countryCode: "IT",
  },
  {
    code: "iu",
    name: "Inuktitut",
    nativeName: "ᐃᓄᒃᑎᑐᑦ",
    countryCode: "CA",
  },
  {
    code: "jp",
    name: "Japanese",
    nativeName: "日本語 (にほんご／にっぽんご)",
    countryCode: "JP",
  },
  {
    code: "jv",
    name: "Javanese",
    nativeName: "basa Jawa",
    countryCode: "ID",
  },
  {
    code: "kl",
    name: "Kalaallisut, Greenlandic",
    nativeName: "kalaallisut, kalaallit oqaasii",
    countryCode: "GL",
  },
  {
    code: "kn",
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
    countryCode: "IN",
  },
  {
    code: "kr",
    name: "Kanuri",
    nativeName: "Kanuri",
    countryCode: "NG",
  },
  {
    code: "ks",
    name: "Kashmiri",
    nativeName: "कश्मीरी, كشميري",
    countryCode: "IN",
  },
  {
    code: "kk",
    name: "Kazakh",
    nativeName: "Қазақ тілі",
    countryCode: "KZ",
  },
  {
    code: "kh",
    name: "Khmer",
    nativeName: "ភាសាខ្មែរ",
    countryCode: "KH",
  },
  {
    code: "ki",
    name: "Kikuyu, Gikuyu",
    nativeName: "Gĩkũyũ",
    countryCode: "KE",
  },
  {
    code: "rw",
    name: "Kinyarwanda",
    nativeName: "Ikinyarwanda",
    countryCode: "RW",
  },
  {
    code: "ky",
    name: "Kirghiz, Kyrgyz",
    nativeName: "кыргыз тили",
    countryCode: "KG",
  },
  {
    code: "kv",
    name: "Komi",
    nativeName: "коми кыв",
    countryCode: "RU",
  },
  {
    code: "kg",
    name: "Kongo",
    nativeName: "KiKongo",
    countryCode: "CD",
  },
  {
    code: "ko",
    name: "Korean",
    nativeName: "한국어 (韓國語), 조선말 (朝鮮語)",
    countryCode: "KR",
  },
  {
    code: "ku",
    name: "Kurdish",
    nativeName: "Kurdî, كوردی",
    countryCode: "IR",
  },
  {
    code: "kj",
    name: "Kwanyama, Kuanyama",
    nativeName: "Kuanyama",
    countryCode: "AO",
  },
  {
    code: "la",
    name: "Latin",
    nativeName: "latine, lingua latina",
    countryCode: "ES",
  },
  {
    code: "lb",
    name: "Luxembourgish, Letzeburgesch",
    nativeName: "Lëtzebuergesch",
    countryCode: "LU",
  },
  {
    code: "lg",
    name: "Luganda",
    nativeName: "Luganda",
    countryCode: "UG",
  },
  {
    code: "li",
    name: "Limburgish, Limburgan, Limburger",
    nativeName: "Limburgs",
    countryCode: "NL",
  },
  {
    code: "ln",
    name: "Lingala",
    nativeName: "Lingála",
    countryCode: "CD",
  },
  {
    code: "lo",
    name: "Lao",
    nativeName: "ພາສາລາວ",
    countryCode: "LA",
  },
  {
    code: "lt",
    name: "Lithuanian",
    nativeName: "lietuvių kalba",
    countryCode: "LT",
  },
  {
    code: "lu",
    name: "Luba-Katanga",
    countryCode: "CD",
  },
  {
    code: "lv",
    name: "Latvian",
    nativeName: "latviešu valoda",
    countryCode: "LV",
  },
  {
    code: "gv",
    name: "Manx",
    nativeName: "Gaelg, Gailck",
    countryCode: "IM",
  },
  {
    code: "mk",
    name: "Macedonian",
    nativeName: "македонски јазик",
    countryCode: "MK",
  },
  {
    code: "mg",
    name: "Malagasy",
    nativeName: "Malagasy fiteny",
    countryCode: "MG",
  },
  {
    code: "ms",
    name: "Malay",
    nativeName: "Bahasa Melayu",
    countryCode: "MY",
  },
  {
    code: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
    countryCode: "IN",
  },
  {
    code: "mt",
    name: "Maltese",
    nativeName: "Malti",
    countryCode: "MT",
  },
  {
    code: "mi",
    name: "Māori",
    nativeName: "te reo Māori",
    countryCode: "NZ",
  },
  {
    code: "mr",
    name: "Marathi (Marāṭhī)",
    nativeName: "मराठी",
    countryCode: "IN",
  },
  {
    code: "mh",
    name: "Marshallese",
    nativeName: "Kajin M̧ajeļ",
    countryCode: "MH",
  },
  {
    code: "mn",
    name: "Mongolian",
    nativeName: "монгол",
    countryCode: "MN",
  },
  {
    code: "na",
    name: "Nauru",
    nativeName: "Ekakairũ Naoero",
    countryCode: "NR",
  },
  {
    code: "nv",
    name: "Navajo, Navaho",
    nativeName: "Diné bizaad, Dinékʼehǰí",
    countryCode: "US",
  },
  {
    code: "nb",
    name: "Norwegian Bokmål",
    nativeName: "Norsk bokmål",
    countryCode: "NO",
  },
  {
    code: "nd",
    name: "North Ndebele",
    nativeName: "isiNdebele",
    countryCode: "ZW",
  },
  {
    code: "ne",
    name: "Nepali",
    nativeName: "नेपाली",
    countryCode: "NP",
  },
  {
    code: "ng",
    name: "Ndonga",
    nativeName: "Owambo",
    countryCode: "AO",
  },
  {
    code: "nn",
    name: "Norwegian Nynorsk",
    nativeName: "Norsk nynorsk",
    countryCode: "NO",
  },
  {
    code: "no",
    name: "Norwegian",
    nativeName: "Norsk",
    countryCode: "NO",
  },
  {
    code: "ii",
    name: "Nuosu",
    nativeName: "ꆈꌠ꒿ Nuosuhxop",
    countryCode: "CN",
  },
  {
    code: "nr",
    name: "South Ndebele",
    nativeName: "isiNdebele",
    countryCode: "ZA",
  },
  {
    code: "oc",
    name: "Occitan",
    nativeName: "Occitan",
    countryCode: "FR",
  },
  {
    code: "oj",
    name: "Ojibwe, Ojibwa",
    nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
    countryCode: "US",
  },
  {
    code: "cu",
    name: "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
    nativeName: "ѩзыкъ словѣньскъ",
    countryCode: "RU",
  },
  {
    code: "om",
    name: "Oromo",
    nativeName: "Afaan Oromoo",
    countryCode: "ET",
  },
  {
    code: "or",
    name: "Oriya",
    nativeName: "ଓଡ଼ିଆ",
    countryCode: "IN",
  },
  {
    code: "os",
    name: "Ossetian, Ossetic",
    nativeName: "ирон æвзаг",
    countryCode: "RU",
  },
  {
    code: "pa",
    name: "Panjabi, Punjabi",
    nativeName: "ਪੰਜਾਬੀ, پنجابی",
    countryCode: "IN",
  },
  {
    code: "pi",
    name: "Pāli",
    nativeName: "पाऴि",
    countryCode: "LK",
  },
  {
    code: "fa",
    name: "Persian",
    nativeName: "فارسی",
    countryCode: "IR",
  },
  {
    code: "pl",
    name: "Polish",
    nativeName: "polski",
    countryCode: "PL",
  },
  {
    code: "ps",
    name: "Pashto, Pushto",
    nativeName: "پښتو",
    countryCode: "AF",
  },
  {
    code: "pt",
    name: "Portuguese",
    nativeName: "Português",
    countryCode: "PT",
  },
  {
    code: "qu",
    name: "Quechua",
    nativeName: "Runa Simi, Kichwa",
    countryCode: "US",
  },
  {
    code: "rm",
    name: "Romansh",
    nativeName: "rumantsch grischun",
    countryCode: "CH",
  },
  {
    code: "rn",
    name: "Kirundi",
    nativeName: "kiRundi",
    countryCode: "BI",
  },
  {
    code: "ro",
    name: "Romanian, Moldavian, Moldovan",
    nativeName: "română",
    countryCode: "RO",
  },
  {
    code: "ru",
    name: "Russian",
    nativeName: "русский язык",
    countryCode: "RU",
  },
  {
    code: "sa",
    name: "Sanskrit (Saṁskṛta)",
    nativeName: "संस्कृतम्",
    countryCode: "IN",
  },
  {
    code: "sc",
    name: "Sardinian",
    nativeName: "sardu",
    countryCode: "IT",
  },
  {
    code: "sd",
    name: "Sindhi",
    nativeName: "सिन्धी, سنڌي، سندھی",
    countryCode: "PK",
  },
  {
    code: "se",
    name: "Northern Sami",
    nativeName: "Davvisámegiella",
    countryCode: "NO",
  },
  {
    code: "sm",
    name: "Samoan",
    nativeName: "gagana faa Samoa",
    countryCode: "WS",
  },
  {
    code: "sg",
    name: "Sango",
    nativeName: "yângâ tî sängö",
    countryCode: "CF",
  },
  {
    code: "sr",
    name: "Serbian",
    nativeName: "српски језик",
    countryCode: "RS",
  },
  {
    code: "gd",
    name: "Scottish Gaelic; Gaelic",
    nativeName: "Gàidhlig",
    countryCode: "GB",
  },
  {
    code: "sn",
    name: "Shona",
    nativeName: "chiShona",
    countryCode: "ZW",
  },
  {
    code: "si",
    name: "Sinhala, Sinhalese",
    nativeName: "සිංහල",
    countryCode: "LK",
  },
  {
    code: "sk",
    name: "Slovak",
    nativeName: "slovenčina",
    countryCode: "SK",
  },
  {
    code: "sl",
    name: "Slovene",
    nativeName: "slovenščina",
    countryCode: "SI",
  },
  {
    code: "so",
    name: "Somali",
    nativeName: "Soomaaliga, af Soomaali",
    countryCode: "SO",
  },
  {
    code: "st",
    name: "Southern Sotho",
    nativeName: "Sesotho",
    countryCode: "ZA",
  },
  {
    code: "es",
    name: "Spanish; Castilian",
    nativeName: "español, castellano",
    countryCode: "ES",
  },
  {
    code: "su",
    name: "Sundanese",
    nativeName: "Basa Sunda",
    countryCode: "ID",
  },
  {
    code: "sw",
    name: "Swahili",
    nativeName: "Kiswahili",
    countryCode: "KE",
  },
  {
    code: "ss",
    name: "Swati",
    nativeName: "SiSwati",
    countryCode: "SZ",
  },
  {
    code: "sv",
    name: "Swedish",
    nativeName: "svenska",
    countryCode: "SE",
  },
  {
    code: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    countryCode: "IN",
  },
  {
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    countryCode: "IN",
  },
  {
    code: "tg",
    name: "Tajik",
    nativeName: "тоҷикӣ, toğikī, تاجیکی",
    countryCode: "TJ",
  },
  {
    code: "th",
    name: "Thai",
    nativeName: "ไทย",
    countryCode: "TH",
  },
  {
    code: "ti",
    name: "Tigrinya",
    nativeName: "ትግርኛ",
    countryCode: "ER",
  },
  {
    code: "bo",
    name: "Tibetan Standard, Tibetan, Central",
    nativeName: "བོད་ཡིག",
    countryCode: "CN",
  },
  {
    code: "tk",
    name: "Turkmen",
    nativeName: "Türkmen, Түркмен",
    countryCode: "TM",
  },
  {
    code: "tl",
    name: "Tagalog",
    nativeName: "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔",
    countryCode: "PH",
  },
  {
    code: "tn",
    name: "Tswana",
    nativeName: "Setswana",
    countryCode: "BW",
  },
  {
    code: "to",
    name: "Tonga (Tonga Islands)",
    nativeName: "faka Tonga",
    countryCode: "TO",
  },
  {
    code: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
    countryCode: "TR",
  },
  {
    code: "ts",
    name: "Tsonga",
    nativeName: "Xitsonga",
    countryCode: "ZA",
  },
  {
    code: "tt",
    name: "Tatar",
    nativeName: "татарча, tatarça, تاتارچا",
    countryCode: "RU",
  },
  {
    code: "tw",
    name: "Twi",
    nativeName: "Twi",
    countryCode: "GH",
  },
  {
    code: "ty",
    name: "Tahitian",
    nativeName: "Reo Tahiti",
    countryCode: "FR",
  },
  {
    code: "ug",
    name: "Uighur, Uyghur",
    nativeName: "Uyƣurqə, ئۇيغۇرچە",
    countryCode: "CN",
  },
  {
    code: "uk",
    name: "Ukrainian",
    nativeName: "українська",
    countryCode: "UA",
  },
  {
    code: "ur",
    name: "Urdu",
    nativeName: "اردو",
    countryCode: "PK",
  },
  {
    code: "uz",
    name: "Uzbek",
    nativeName: "zbek, Ўзбек, أۇزبېك",
    countryCode: "UZ",
  },
  {
    code: "ve",
    name: "Venda",
    nativeName: "Tshivenḓa",
    countryCode: "ZA",
  },
  {
    code: "vn",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
    countryCode: "VN",
  },
  {
    code: "vo",
    name: "Volapük",
    nativeName: "Volapük",
    countryCode: "GO",
  },
  {
    code: "wa",
    name: "Walloon",
    nativeName: "Walon",
    countryCode: "BE",
  },
  {
    code: "cy",
    name: "Welsh",
    nativeName: "Cymraeg",
    countryCode: "GB",
  },
  {
    code: "wo",
    name: "Wolof",
    nativeName: "Wollof",
    countryCode: "SN",
  },
  {
    code: "fy",
    name: "Western Frisian",
    nativeName: "Frysk",
    countryCode: "NL",
  },
  {
    code: "xh",
    name: "Xhosa",
    nativeName: "isiXhosa",
    countryCode: "ZA",
  },
  {
    code: "yi",
    name: "Yiddish",
    nativeName: "ייִדיש",
    countryCode: "RU",
  },
  {
    code: "yo",
    name: "Yoruba",
    nativeName: "Yorùbá",
    countryCode: "BI",
  },
  {
    code: "za",
    name: "Zhuang, Chuang",
    nativeName: "Saɯ cueŋƅ, Saw cuengh",
    countryCode: "CN",
  },
];

export default languages;
